import type { Metadata } from "next";
import { Instrument_Serif } from "next/font/google";
import "./globals.css";

const InstrumentSerif = Instrument_Serif({
  variable: "--font-instrument-serif",
  subsets: ["latin"],
  weight: "400",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${InstrumentSerif.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
